#!/usr/bin/env bash
# ============================================================
# SoundScore — Self-Hosting Setup
# Generates a secure .env and starts the application
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "========================================"
echo "  SoundScore — Self-Hosting Setup"
echo "========================================"
echo ""

# ── Generate .env if it doesn't exist ─────────────────
if [ -f .env ]; then
    echo "[!] .env already exists — skipping generation."
    echo "    Delete .env first if you want fresh secrets."
else
    echo "[+] Generating fresh .env ..."

    DB_PASSWORD=$(openssl rand -base64 32 | tr -d '/+' | head -c 24)
    JWT_SECRET=$(openssl rand -base64 64)

    cat > .env <<EOF
# ============================================================
# SoundScore — Self-Hosting Configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not commit this file!
# ============================================================

# ── Database ──────────────────────────────────────────
DB_ROOT_PASSWORD=${DB_PASSWORD}
DB_NAME=sound

# ── JWT ──────────────────────────────────────────────
JWT_SECRET_KEY=${JWT_SECRET}

# ── Mail (optional, leave empty to skip email) ───────
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=

# ── Seeding ──────────────────────────────────────────
SEEDING_ENABLED=true

# ── CORS (comma-separated) ───────────────────────────
CORS_ALLOWED_ORIGINS=http://localhost:4200

# ── App Port ─────────────────────────────────────────
APP_PORT=8888

# ── Cloudflare Tunnel (optional) ─────────────────────
# Get token: cloudflared tunnel token 8e20f0f1-e3dc-466e-9b44-e4c84cd5cdce
CLOUDFLARE_TUNNEL_TOKEN=
EOF

    echo "    ✓ .env generated"
fi

echo ""

# ── Check for tunnel token ────────────────────────────
source .env 2>/dev/null || true
COMPOSE_ARGS="up -d --build"

if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
    COMPOSE_ARGS="--profile tunnel up -d --build"
    echo "[+] Cloudflare Tunnel token found — public access enabled"
    echo "    → https://soundscore.chlarc.ch"
else
    echo "[i] No CLOUDFLARE_TUNNEL_TOKEN set — local-only mode"
    echo "    → http://localhost:${APP_PORT:-8888}"
fi
echo ""

# ── Start the application ────────────────────────────
echo "[+] Starting SoundScore ..."
echo ""
docker compose ${COMPOSE_ARGS}

echo ""
echo "========================================"
echo "  SoundScore is running!"
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
    echo "  Local : http://localhost:${APP_PORT:-8888}"
    echo "  Public: https://soundscore.chlarc.ch"
else
    echo "  → http://localhost:${APP_PORT:-8888}"
fi
echo "========================================"
echo ""
echo "  Default test accounts (when seeded):"
echo "    alice / password123"
echo "    bob   / password123"
echo ""
echo "  To stop:  docker compose down"
echo ""
